name: Deploy to AWS

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # the container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1

      - name: npm install & build
        run: |
          npm install
          npm run build

      - name: S3 sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: $(( secrets.AWS_S3_BUCKET ))
          AWS_ACCESS_KEY_ID: $(( secrets.AWS_ACCESS_KEY_ID ))
          AWS_SECRET_ACCESS_KEY: $(( secrets.AWS_SECRET_ACCESS_KEY ))
          AWS_REGION: $(( secrets.AWS_REGION ))
          SOURCE_DIR: 'dist'

      - name: Invalid cloudfront
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION ))
          PATHS: '/*'
          AWS_ACCESS_KEY_ID: $(( secrets.AWS_ACCESS_KEY_ID ))
          AWS_SECRET_ACCESS_KEY: $(( secrets.AWS_SECRET_ACCESS_KEY ))
          AWS_REGION: $(( secrets.AWS_REGION ))
